### ISSUE TITLE
[BUG] GetNumSupportedArchs GetSupportedArchs compile error

### ISSUE THREAD

**Issue by Xseventh** [NVIDIA/jitify#110]
template arguments nvrtcProgram is not correct, should remove it.
https://github.com/NVIDIA/jitify/blob/0efec9374e640a80968941d7037ee839e8947b2c/jitify2.hpp#L2392
https://github.com/NVIDIA/jitify/blob/0efec9374e640a80968941d7037ee839e8947b2c/jitify2.hpp#L2396

**Comment by Xseventh** [comment]
more compile info: 
compile with cuda-toolkit 11.0
#define JITIFY_LINK_NVRTC_STATIC 1
#define JITIFY_LINK_CUDA_STATIC 1

get compile error:
jitify2.hpp:2560:62: error: cannot convert 'int*' to '_nvrtcProgram*' in argument passing nvrtc().GetNumSupportedArchs()(&num_supported_archs);

**Comment by benbarsdell** [comment]
Fixed by https://github.com/NVIDIA/jitify/pull/111. Closing.
